import { useEffect, useState, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';

const InspectionPackView = () => {
  const { token, user, loading: authLoading } = useContext(AuthContext);
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (authLoading) return;
    if (!token) { navigate('/login'); return; }

    const fetchReadiness = async () => {
      try {
        const res = await axios.get('http://localhost:5000/api/inspection/readiness', {
          headers: { Authorization: `Bearer ${token}` }
        });
        setData(res.data.data);
        
        // Give time for React to render before printing
        setTimeout(() => {
          window.print();
        }, 1000);
      } catch (err: any) {
        if (err.response?.status === 401) navigate('/login');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchReadiness();
  }, [token, authLoading, navigate]);

  if (authLoading || loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', color: '#666', background: '#fff' }}>
        <Loader2 className="spin" size={32} />
        <span style={{ marginLeft: 12 }}>Generating Inspection Pack...</span>
      </div>
    );
  }

  if (!data) return <div style={{ color: '#000', background: '#fff', padding: 20 }}>Failed to load inspection data.</div>;

  const unverifiedEvidence = data.evidenceIndex?.filter((ev: any) => ev.verificationStatus === 'UNVERIFIED' || ev.verificationStatus === 'UNDER_REVIEW') || [];

  return (
    <div style={{ background: '#fff', color: '#000', minHeight: '100vh', padding: '40px', fontFamily: 'system-ui, sans-serif' }}>
      <style>
        {`
          @media print {
            body { background: #fff !important; color: #000 !important; }
            .page-break { page-break-before: always; }
            .no-print { display: none !important; }
            * { box-shadow: none !important; }
          }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px; }
          th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; vertical-align: top; }
          th { background: #f5f5f5; font-weight: 600; }
          h1, h2, h3 { color: #111; margin-top: 24px; margin-bottom: 12px; }
          .badge-status { padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: 500; }
          .badge-success { background: #e6f4ea; color: #137333; }
          .badge-warning { background: #fef7e0; color: #b06000; }
          .badge-danger { background: #fce8e6; color: #c5221f; }
          .badge-default { background: #f1f3f4; color: #3c4043; }
        `}
      </style>

      <div style={{ textAlign: 'center', marginBottom: '40px', borderBottom: '2px solid #000', paddingBottom: '20px' }}>
        <h1 style={{ margin: '0 0 8px', fontSize: '24px' }}>COMPLIANCE INSPECTION PACK</h1>
        <p style={{ margin: 0, fontSize: '14px', color: '#555' }}>Internal Preparation Document</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '40px' }}>
        <div>
          <h3 style={{ marginTop: 0 }}>Business Information</h3>
          <p><strong>Business Name:</strong> {user?.name || 'Authorized Business'}</p>
          <p><strong>Generated By:</strong> {user?.email}</p>
          <p><strong>Generated At:</strong> {new Date().toLocaleString()}</p>
        </div>
        <div>
          <h3 style={{ marginTop: 0 }}>Inspection Readiness</h3>
          <p><strong>Status:</strong> {data.readinessStatus.replace('_', ' ')}</p>
          <p><strong>Calculated Score:</strong> {data.readinessScore}%</p>
          <p><strong>Required Documents:</strong> {data.metrics.totalRequired}</p>
        </div>
      </div>

      {data.criticalGaps && data.criticalGaps.length > 0 && (
        <div style={{ marginBottom: '40px', padding: '16px', border: '1px solid #c5221f', background: '#fff' }}>
          <h2 style={{ color: '#c5221f', marginTop: 0 }}>High-Risk Inspection Items</h2>
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            {data.criticalGaps.map((gap: any, i: number) => (
              <li key={i} style={{ marginBottom: '12px' }}>
                <strong>{gap.issue}:</strong> {gap.obligation} {gap.docType ? `(${gap.docType})` : ''}
                <div style={{ fontSize: '13px', color: '#555', marginTop: '4px', background: '#f5f5f5', padding: '6px', borderRadius: '4px' }}>
                  <strong>Risk:</strong> {gap.whyDoesItMatter || gap.reason} <br/>
                  <strong>Action Required:</strong> {gap.whatShouldIDo || 'Resolve immediately'} <br/>
                  <strong>Regulatory Source:</strong> {gap.source || 'Suraksha Rules'}
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      <h2>Missing Required Documents</h2>
      <table>
        <thead>
          <tr>
            <th>Document Type</th>
            <th>Related Obligation</th>
            <th>{t('obl.regulatorySource', 'Regulatory Source')}</th>
            <th>Responsible</th>
          </tr>
        </thead>
        <tbody>
          {data.missingDocuments && data.missingDocuments.map((doc: any, i: number) => (
            <tr key={i}>
              <td><span style={{ color: '#c5221f', fontWeight: 'bold' }}>{doc.documentType}</span></td>
              <td>{doc.obligationTitle} ({doc.obligationCode})</td>
              <td>{doc.regulatorySource ? `${doc.regulatorySource.actName} Sec ${doc.regulatorySource.section}` : 'Suraksha Rules'}</td>
              <td>{doc.assignedTo ? doc.assignedTo.name : 'Unassigned'}</td>
            </tr>
          ))}
          {(!data.missingDocuments || data.missingDocuments.length === 0) && (
            <tr><td colSpan={4} style={{ textAlign: 'center' }}>No missing documents.</td></tr>
          )}
        </tbody>
      </table>

      <div className="page-break">
        <h2>Inspection Checklist (Applicable Obligations)</h2>
        <table>
          <thead>
            <tr>
              <th>Rule Code</th>
              <th>{t("obl.obligation", "Obligation")}</th>
              <th>{t("obl.severity", "Severity")}</th>
              <th>Submission Status</th>
              <th>{t('obl.regulatorySource', 'Regulatory Source')}</th>
            </tr>
          </thead>
          <tbody>
            {data.checklist && data.checklist.map((item: any, i: number) => (
              <tr key={i}>
                <td>{item.ruleCode}</td>
                <td>{item.obligationName}</td>
                <td>{item.severity}</td>
                <td>{item.submissionStatus.replace(/_/g, ' ')}</td>
                <td>{item.regulatorySource?.actName || 'N/A'}</td>
              </tr>
            ))}
            {(!data.checklist || data.checklist.length === 0) && (
              <tr><td colSpan={5} style={{ textAlign: 'center' }}>No applicable obligations found.</td></tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="page-break">
        <h2>Evidence Index</h2>
        <table>
          <thead>
            <tr>
              <th>Document Name</th>
              <th>Type</th>
              <th>{t("obl.obligation", "Obligation")}</th>
              <th>Verification Status</th>
              <th>Expiry Date</th>
            </tr>
          </thead>
          <tbody>
            {data.evidenceIndex && data.evidenceIndex.map((ev: any, i: number) => (
              <tr key={i}>
                <td>{ev.name}</td>
                <td>{ev.type}</td>
                <td>{ev.obligationCode}</td>
                <td>{ev.verificationStatus}</td>
                <td style={{ color: ev.verificationStatus === 'EXPIRED' ? '#c5221f' : 'inherit' }}>
                  {ev.expiryDate ? new Date(ev.expiryDate).toLocaleDateString() : 'N/A'}
                </td>
              </tr>
            ))}
            {(!data.evidenceIndex || data.evidenceIndex.length === 0) && (
              <tr><td colSpan={5} style={{ textAlign: 'center' }}>No evidence uploaded.</td></tr>
            )}
          </tbody>
        </table>
      </div>

      {unverifiedEvidence.length > 0 && (
        <div className="page-break">
          <h2>Evidence Requiring Human Review</h2>
          <table>
            <thead>
              <tr>
                <th>Document Name</th>
                <th>Type</th>
                <th>{t("obl.obligation", "Obligation")}</th>
                <th>Uploaded By</th>
              </tr>
            </thead>
            <tbody>
              {unverifiedEvidence.map((ev: any, i: number) => (
                <tr key={i}>
                  <td>{ev.name}</td>
                  <td>{ev.type}</td>
                  <td>{ev.obligationCode}</td>
                  <td>{ev.responsibleUser}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {(data.overdueActions?.length > 0 || data.upcomingActions?.length > 0) && (
        <div className="page-break">
          <h2>Open Corrective Actions</h2>
          <table>
            <thead>
              <tr>
                <th>Action Title</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Responsible</th>
              </tr>
            </thead>
            <tbody>
              {data.overdueActions?.map((action: any, i: number) => (
                <tr key={`od-${i}`}>
                  <td>{action.title}</td>
                  <td style={{ color: '#c5221f', fontWeight: 'bold' }}>{new Date(action.dueDate).toLocaleDateString()}</td>
                  <td><span className="badge-status badge-danger">OVERDUE</span></td>
                  <td>{action.assignedTo?.name || 'Unassigned'}</td>
                </tr>
              ))}
              {data.upcomingActions?.map((action: any, i: number) => (
                <tr key={`up-${i}`}>
                  <td>{action.title}</td>
                  <td>{new Date(action.dueDate).toLocaleDateString()}</td>
                  <td><span className="badge-status badge-default">PENDING</span></td>
                  <td>{action.assignedTo?.name || 'Unassigned'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {data.recentUpdates && data.recentUpdates.length > 0 && (
        <div className="page-break">
          <h2>Recent Regulatory Changes</h2>
          {data.recentUpdates.map((update: any, i: number) => (
            <div key={i} style={{ borderBottom: '1px solid #eee', paddingBottom: '12px', marginBottom: '12px' }}>
              <h4 style={{ margin: '0 0 4px' }}>{update.title}</h4>
              <p style={{ margin: '0 0 8px', fontSize: '14px', color: '#444' }}>{update.summary}</p>
              <div style={{ fontSize: '12px', color: '#666' }}>
                Effective: {update.effectiveDate ? new Date(update.effectiveDate).toLocaleDateString() : 'N/A'} | Source: {update.sourceId?.name || 'Government Gazette'}
              </div>
            </div>
          ))}
        </div>
      )}

      <div style={{ marginTop: '60px', paddingTop: '20px', borderTop: '1px solid #ccc', fontSize: '12px', color: '#666', textAlign: 'center' }}>
        <p>This report was automatically generated by SurakshaSetu AI.</p>
        <p>This is an internal preparation document and does not constitute official legal clearance or government certification.</p>
      </div>
      
      <div className="no-print" style={{ position: 'fixed', bottom: 20, right: 20 }}>
        <button onClick={() => window.close()} style={{ padding: '8px 16px', background: '#333', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Close Preview</button>
      </div>
    </div>
  );
};

export default InspectionPackView;
