import { useEffect, useState, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { Loader2 } from 'lucide-react';

const InspectionPackView = () => {
  const { token, user, loading: authLoading } = useContext(AuthContext);
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (authLoading) return;
    if (!token) { navigate('/login'); return; }

    const fetchReadiness = async () => {
      try {
        const res = await axios.get('http://localhost:5000/api/inspection/readiness', {
          headers: { Authorization: `Bearer ${token}` }
        });
        setData(res.data.data);
        
        // Give time for React to render before printing
        setTimeout(() => {
          window.print();
        }, 1000);
      } catch (err: any) {
        if (err.response?.status === 401) navigate('/login');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchReadiness();
  }, [token, authLoading, navigate]);

  if (authLoading || loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', color: '#666', background: '#fff' }}>
        <Loader2 className="spin" size={32} />
        <span style={{ marginLeft: 12 }}>Generating Inspection Pack...</span>
      </div>
    );
  }

  if (!data) return <div style={{ color: '#000', background: '#fff', padding: 20 }}>Failed to load inspection data.</div>;

  return (
    <div style={{ background: '#fff', color: '#000', minHeight: '100vh', padding: '40px', fontFamily: 'system-ui, sans-serif' }}>
      {/* Print styles block to hide UI elements if accessed directly, ensure nice page breaks */}
      <style>
        {`
          @media print {
            body { background: #fff !important; color: #000 !important; }
            .page-break { page-break-before: always; }
            .no-print { display: none !important; }
            * { box-shadow: none !important; }
          }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
          th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }
          th { background: #f5f5f5; font-weight: 600; }
          h1, h2, h3 { color: #111; margin-top: 24px; margin-bottom: 12px; }
          .badge-status { padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: 500; }
          .badge-success { background: #e6f4ea; color: #137333; }
          .badge-warning { background: #fef7e0; color: #b06000; }
          .badge-danger { background: #fce8e6; color: #c5221f; }
          .badge-default { background: #f1f3f4; color: #3c4043; }
        `}
      </style>

      <div style={{ textAlign: 'center', marginBottom: '40px', borderBottom: '2px solid #000', paddingBottom: '20px' }}>
        <h1 style={{ margin: '0 0 8px', fontSize: '24px' }}>COMPLIANCE INSPECTION PACK</h1>
        <p style={{ margin: 0, fontSize: '14px', color: '#555' }}>Internal Preparation Document</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '40px' }}>
        <div>
          <h3 style={{ marginTop: 0 }}>Business Information</h3>
          <p><strong>Business Name:</strong> {user?.name || 'Authorized Business'}</p>
          <p><strong>Generated By:</strong> {user?.email}</p>
          <p><strong>Generated At:</strong> {new Date().toLocaleString()}</p>
        </div>
        <div>
          <h3 style={{ marginTop: 0 }}>Inspection Readiness</h3>
          <p><strong>Status:</strong> {data.readinessStatus.replace('_', ' ')}</p>
          <p><strong>Calculated Score:</strong> {data.readinessScore}%</p>
          <p><strong>Required Documents:</strong> {data.metrics.totalRequired}</p>
        </div>
      </div>

      {data.criticalGaps.length > 0 && (
        <div style={{ marginBottom: '40px', padding: '16px', border: '1px solid #c5221f', background: '#fff' }}>
          <h2 style={{ color: '#c5221f', marginTop: 0 }}>Critical Gaps Identified</h2>
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            {data.criticalGaps.map((gap: any, i: number) => (
              <li key={i} style={{ marginBottom: '8px' }}>
                <strong>{gap.issue}:</strong> {gap.obligation} {gap.docType ? `(${gap.docType})` : ''}
              </li>
            ))}
          </ul>
        </div>
      )}

      <h2>Required Document Checklist</h2>
      <table>
        <thead>
          <tr>
            <th>Document Type</th>
            <th>Related Obligation</th>
            <th>Status</th>
            <th>Expiry Date</th>
          </tr>
        </thead>
        <tbody>
          {data.documentChecklist.map((doc: any, i: number) => {
            let badgeClass = 'badge-default';
            if (doc.status === 'VERIFIED') badgeClass = 'badge-success';
            if (doc.status === 'MISSING' || doc.status === 'EXPIRED') badgeClass = 'badge-danger';
            if (doc.status === 'PENDING') badgeClass = 'badge-warning';

            return (
              <tr key={i}>
                <td>{doc.documentType}</td>
                <td>{doc.obligationTitle}</td>
                <td><span className={`badge-status ${badgeClass}`}>{doc.status}</span></td>
                <td>{doc.expiryDate ? new Date(doc.expiryDate).toLocaleDateString() : 'N/A'}</td>
              </tr>
            );
          })}
          {data.documentChecklist.length === 0 && (
            <tr><td colSpan={4} style={{ textAlign: 'center' }}>No specific documents strictly required by current configured rules.</td></tr>
          )}
        </tbody>
      </table>

      {(data.overdueActions.length > 0 || data.upcomingActions.length > 0) && (
        <div className="page-break">
          <h2>Pending Compliance Actions</h2>
          <table>
            <thead>
              <tr>
                <th>Action Title</th>
                <th>Due Date</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {data.overdueActions.map((action: any, i: number) => (
                <tr key={`od-${i}`}>
                  <td>{action.title}</td>
                  <td style={{ color: '#c5221f', fontWeight: 'bold' }}>{new Date(action.dueDate).toLocaleDateString()}</td>
                  <td><span className="badge-status badge-danger">OVERDUE</span></td>
                </tr>
              ))}
              {data.upcomingActions.map((action: any, i: number) => (
                <tr key={`up-${i}`}>
                  <td>{action.title}</td>
                  <td>{new Date(action.dueDate).toLocaleDateString()}</td>
                  <td><span className="badge-status badge-default">PENDING</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {data.recentUpdates.length > 0 && (
        <div className="page-break">
          <h2>Recent Regulatory Changes</h2>
          {data.recentUpdates.map((update: any, i: number) => (
            <div key={i} style={{ borderBottom: '1px solid #eee', paddingBottom: '12px', marginBottom: '12px' }}>
              <h4 style={{ margin: '0 0 4px' }}>{update.title}</h4>
              <p style={{ margin: '0 0 8px', fontSize: '14px', color: '#444' }}>{update.summary}</p>
              <div style={{ fontSize: '12px', color: '#666' }}>
                Effective: {update.effectiveDate ? new Date(update.effectiveDate).toLocaleDateString() : 'N/A'} | Source: {update.sourceId?.name || 'Government Gazette'}
              </div>
            </div>
          ))}
        </div>
      )}

      <div style={{ marginTop: '60px', paddingTop: '20px', borderTop: '1px solid #ccc', fontSize: '12px', color: '#666', textAlign: 'center' }}>
        <p>This report was automatically generated by SurakshaSetu AI.</p>
        <p>This is an internal preparation document and does not constitute official legal clearance or government certification.</p>
      </div>
      
      <div className="no-print" style={{ position: 'fixed', bottom: 20, right: 20 }}>
        <button onClick={() => window.close()} style={{ padding: '8px 16px', background: '#333', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Close Preview</button>
      </div>
    </div>
  );
};

export default InspectionPackView;
